name: Deploy Products Services to EC2

on:
  push:
    branches:
      - QA

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Set up SSH key for EC2
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker images for login and register services
      run: |
        docker build -t chamorrito/review ./Reviews
        docker build -t chamorrito/get_review ./Get_review
        docker build -t chamorrito/cart ./Cart

    - name: Push images to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push chamorrito/review
        docker push chamorrito/get_review
        docker push chamorrito/cart

    - name: Deploy services to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 98.85.200.29 
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # De
          docker stop review || true
          docker rm review || true
          docker stop get_review || true
          docker rm get_review || true
          docker stop cart || true
          docker rm cart || true

          # D
          docker pull chamorrito/review
          docker pull chamorrito/get_review
          docker pull chamorrito/cart

          # Eje
          docker run -d --name review -p 5000:5000 --restart unless-stopped chamorrito/review
          docker run -d --name get_review -p 5001:5001 --restart unless-stopped chamorrito/get_review
          docker run -d --name cart -p 5002:5002 --restart unless-stopped chamorrito/cart